### ISSUE TITLE
Batch resave instruments recursively without loading

### ISSUE THREAD

**Issue by aminya** [monomadic/ni-file#5]
Hi, I find this project interesting. I think this project allows doing very useful things. For example, one of the main issues I have is that for batch-resaving libraries, I need to load and resave each library manually (which usually takes a lot of time). It seems that all the instrument files are doing is storing the paths to the samples of a library. So, if we can find a way to modify the files, we can automate the process and add the paths and improve the loading speed significantly.

**Comment by monomadic** [comment]
Yes, this will be achievable with this library eventually, but its purpose has been to document the file formats, and provide a library to other utilities so that they built utilities that do things like this.

Right now the Kontakt formats are being reversed, and reading them will be in the first release. Writing will come after.

**Comment by aminya** [comment]
Thanks! I'll close this then now
